Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: discord.py in ./.local/lib/python3.9/site-packages (1.7.3)
Requirement already satisfied: aiohttp<3.8.0,>=3.6.0 in ./.local/lib/python3.9/site-packages (from discord.py) (3.7.4.post0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.local/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (5.2.0)
Requirement already satisfied: chardet<5.0,>=2.0 in ./.local/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (4.0.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./.local/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in ./.local/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (21.2.0)
Requirement already satisfied: typing-extensions>=3.6.5 in ./.local/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (3.10.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.local/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (1.6.3)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.8.0,>=3.6.0->discord.py) (2.6)
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.
Logged in as altereal.bot (ID: 4WP0JYEd)
------
server has 106 channels.
'<ChannelType.chat> Comment √©crire with 4 messages.'
'<ChannelType.chat> üåê Darknet with 2 messages.'
'<ChannelType.chat> Empathie with 2 messages.'
'<ChannelType.chat> Athl√©tisme with 3 messages.'
'<ChannelType.chat> Entropie with 2 messages.'
'<ChannelType.chat> Bob with 1 messages.'
'<ChannelType.chat> Conseil des traditions with 1 messages.'
'<ChannelType.chat> Mentor with 2 messages.'
'<ChannelType.chat> Influence with 1 messages.'
'<ChannelType.chat> Vie with 2 messages.'
'<ChannelType.chat> Statut with 2 messages.'
'<ChannelType.chat> Alli√©s with 2 messages.'
'<ChannelType.chat> Technologie with 2 messages.'
'<ChannelType.chat> Bagarre with 2 messages.'
'<ChannelType.chat> Raison with 2 messages.'
'<ChannelType.chat> Occultisme with 2 messages.'
'<ChannelType.chat> Dext√©rit√© with 2 messages.'
'<ChannelType.chat> Esprits with 2 messages.'
'<ChannelType.chat> Investigation with 2 messages.'
'<ChannelType.chat> Fausse identit√© with 2 messages.'
'<ChannelType.chat> M√™l√©e with 2 messages.'
'<ChannelType.chat> Forces with 2 messages.'
'<ChannelType.chat> M√©decine with 2 messages.'
'<ChannelType.chat> Prime with 2 messages.'
'<ChannelType.chat> Ressources with 2 messages.'
'<ChannelType.chat> Familier with 2 messages.'
'<ChannelType.chat> üåê Internet with 2 messages.'
'<ChannelType.chat> tests de bot with 50 messages.'
'<ChannelType.chat> Informatique with 2 messages.'
'<ChannelType.chat> Art with 2 messages.'
'<ChannelType.chat> Sondages with 2 messages.'
'<ChannelType.chat> G√©n√©ral (hors jeu) with 50 messages.'
'<ChannelType.chat> √âsot√©risme with 2 messages.'
'<ChannelType.chat> Renomm√©e with 2 messages.'
'<ChannelType.chat> Vigilance with 2 messages.'
'<ChannelType.chat> Artisanats with 2 messages.'
'<ChannelType.chat> Etiquette with 2 messages.'
'<ChannelType.chat> Survie with 2 messages.'
'<ChannelType.chat> Manipulation with 2 messages.'
'<ChannelType.chat> Feuille de perso with 2 messages.'
'<ChannelType.chat> Expression with 2 messages.'
'<ChannelType.chat> Perception with 2 messages.'
'<ChannelType.chat> Id√©es vrac from IRL with 2 messages.'
'<ChannelType.chat> Sillicon Valley - Narration with 1 messages.'
'<ChannelType.chat> M√©ditation with 2 messages.'
'<ChannelType.chat> Yosemite - Narration with 4 messages.'
'<ChannelType.chat> Mati√®re with 2 messages.'
'<ChannelType.chat> Subterfuge with 2 messages.'
'<ChannelType.chat> Commandement with 2 messages.'
'<ChannelType.chat> Alcatraz - Narration with 1 messages.'
'<ChannelType.chat> Sciences with 2 messages.'
'<ChannelType.chat> Empathie with 2 messages.'
'<ChannelType.chat> Charte with 2 messages.'
'<ChannelType.chat> Node with 2 messages.'
'<ChannelType.chat> Exp√©rience de la rue with 2 messages.'
'<ChannelType.chat> Furtivit√© with 2 messages.'
'<ChannelType.chat> M√©moire with 2 messages.'
'<ChannelType.chat> Charisme with 2 messages.'
"<ChannelType.chat> L'union des conventions with 1 messages."
'<ChannelType.chat> Sheet template tests with 5 messages.'
'<ChannelType.chat> Contacts with 2 messages.'
'<ChannelType.chat> √ârudition with 2 messages.'
'<ChannelType.chat> Prodige with 2 messages.'
'<ChannelType.chat> Armes √† feu with 2 messages.'
'<ChannelType.chat> Conduite with 2 messages.'
'<ChannelType.chat> Guilded tips with 3 messages.'
'<ChannelType.chat> Intimidation with 2 messages.'
'<ChannelType.chat> Recherche with 2 messages.'
'<ChannelType.chat> Psych√© with 2 messages.'
'<ChannelType.chat> Droit with 2 messages.'
'<ChannelType.chat> Volont√© with 2 messages.'
'<ChannelType.chat> Downtown - Narration with 1 messages.'
'<ChannelType.chat> Force with 4 messages.'
'<ChannelType.chat> Nom du Personnage with 3 messages.'
'<ChannelType.chat> Rang with 2 messages.'
'<ChannelType.chat> Culte with 2 messages.'
'<ChannelType.chat> general with 14 messages.'
'<ChannelType.chat> Arts martiaux with 2 messages.'
'<ChannelType.chat> Espace with 2 messages.'
'<ChannelType.chat> Temps with 2 messages.'
Ignoring exception in command backupChannels:
Traceback (most recent call last):
  File "/home/minecraft/multicraft/servers/server223117/.local/lib/python3.9/site-packages/guilded/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/minecraft/multicraft/servers/server223117/guilded_altereal.py", line 144, in backupChannels
    await ctx.send(str(len(bakupedDict))+" channels backuped")
NameError: name 'bakupedDict' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/minecraft/multicraft/servers/server223117/.local/lib/python3.9/site-packages/guilded/ext/commands/bot.py", line 452, in invoke
    await ctx.command.invoke(ctx)
  File "/home/minecraft/multicraft/servers/server223117/.local/lib/python3.9/site-packages/guilded/ext/commands/core.py", line 619, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/minecraft/multicraft/servers/server223117/.local/lib/python3.9/site-packages/guilded/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
guilded.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'bakupedDict' is not defined
